### ISSUE TITLE
workflow-controller should have a garbage collection

### ISSUE THREAD

**Issue by sdminonne** [AmadeusITGroup/workflow-controller#22]

**Comment by sdminonne** [comment]
@alexei-led @clamoriniere1A @EricMountain-1A I'm working on it

**Comment by alexei-led** [comment]
@sdminonne Cool, take a look at the `etcd` operator code. They've implemented something similar.

**Comment by clamoriniere1A** [comment]
@sdminonne I think we can close this issue.

**Comment by sdminonne** [comment]
I think :)
