### ISSUE TITLE
API doesn't seem to match the example.

### ISSUE THREAD

**Issue by jhart99** [AmadeusITGroup/workflow-controller#43]
I was having a look at the code for this to implement a python interface for workflows like the kubernetes team does for their APIs.  I noticed that there is a mismatch between the diamond.yaml example and the structures in the Go code.  In the [diamond.yaml](https://github.com/AmadeusITGroup/workflow-controller/blob/master/examples/hello_workflow/diamond.yaml) there is a metadata section as part of WorkflowSpec, but in the [types](https://github.com/AmadeusITGroup/workflow-controller/blob/master/pkg/api/workflow/v1/types.go)  there are only Steps, Selector and ActiveDeadlineSeconds.  It doesn't matter all that much because the diamond example still works correctly, but I just wanted to be sure that I was adding all the fields that were actually in the spec.

**Comment by sdminonne** [comment]
Fixed by #44

**Comment by sdminonne** [comment]
@jhart99 thanks for reporting this! @EricMountain-1A fixed it. :)
